### PR TITLE
Add covid19projects link

### PR DESCRIPTION
**Pull request by happylolonly**

### CODE REVIEW

**Comment by soroushchehresa** [comment]
@happylolonly 
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.

**Comment by happylolonly** [comment]
@soroushchehresa in what file should I add our link? `open-source-projects.json` don't support links

**Comment by happylolonly** [comment]
@soroushchehresa ?

**Comment by soroushchehresa** [comment]
@happylolonly You can place your link under `Applications`/`Web Apps`

**Comment by happylolonly** [comment]
yes, but it is not webapp 🙄

**Comment by soroushchehresa** [comment]
@happylolonly This list just has this position for your URL because that isn't an open-source project!

**Pull request closed without merging**
