### PR TITLE
Add CoronaBoard

### PR DESCRIPTION
**Pull request by soaple**
Add  https://corona-board.soaple.endpoint.ainize.ai/ web app.

This is a global dashboard for monitoring Corona virus developed by using StickyBoard open source project.

### CODE REVIEW

**Comment by soroushchehresa** [comment]
@soaple 
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.

**Comment by soaple** [comment]
> @soaple
> Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.

What's the problem?

**Comment by soaple** [comment]
> @soaple
> Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.

- Place your item at end of the related list. **=> correct**
- Search previous suggestions before making a new one, as yours may be a duplicate. **=> No duplicate**
- Make an individual pull request for each suggestion. **=> correct**
- Keep descriptions short and simple, but descriptive. **=> correct**
- Check your spelling and grammar. **=> correct**
- New categories or improvements to the existing categorization are welcome, but should be done in a separate pull request. **=> Not applicable**

**Comment by soroushchehresa** [comment]
@soaple 
Screen Shot 2020-04-06 at 3 42 47 PM

**Pull request closed without merging**
