### PR TITLE
Added whereiscovid.info

### PR DESCRIPTION
**Pull request by cakebatterandsprinkles**
Made an app to track the spread of COVID19 throughout the whole world and US & read the latest publications on PubMed.

### CODE REVIEW

**Comment by soroushchehresa** [comment]
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.

**Comment by cakebatterandsprinkles** [comment]
Hello soroushchehresa! I read the contribution guidelines again, but I don't see anything wrong with my request. Can you please tell me why you declined so that I can fix it? Thanks.

**Comment by soroushchehresa** [comment]
@cakebatterandsprinkles You should only update `data/*.json`.

**Comment by cakebatterandsprinkles** [comment]
Oh gosh. You are very kind and I am very ashamed. Thank you for answering.

**Comment by soroushchehresa** [comment]
@cakebatterandsprinkles Your welcome.

**Pull request closed without merging**
